export const GET_ERRORS = 'GET_ERRORS';
export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';

export const USER_CONNECTED = 'USER_CONNECTED';
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT';
export const EMIT_TO_SOCKET = 'EMIT_TO_SOCKET';
export const SET_USERNAME = 'SET_USERNAME';
export const SEND_MESSAGE = 'SEND_MESSAGE';

